- README.md
- THEORY.md
Update docs to reflect the new compile_time attribute of chef_gem required to suppress warnings in Chef 12.1.0.
Closes #143
[ciskip]
> Update docs to reflect the new compile_time attribute of chef_gem

- .travis.yml
- Changelog.md
without failing the entire build
> Allow ruby 1.9.3 to fail on Travis

- .rubocop_todo.yml
- Changelog.md
- lib/chef-vault/item.rb
- spec/chef-vault/item_spec.rb
Add a #raw_keys method to ChefVault::Item that returns the keys of the underlying raw data bag item
This is the best we can do without breaking the public API (which can't happen until v3)
Closes #142
> Add a #raw_keys method to ChefVault::Item

- .rubocop_todo.yml
- Changelog.md
- README.md
- bin/chef-vault
- lib/chef-vault/certificate.rb
- lib/chef-vault/item.rb
- lib/chef-vault/user.rb
- lib/chef/knife/decrypt.rb
- lib/chef/knife/encrypt_create.rb
- lib/chef/knife/encrypt_delete.rb
- lib/chef/knife/encrypt_remove.rb
- lib/chef/knife/encrypt_rotate_keys.rb
- lib/chef/knife/encrypt_update.rb
- lib/chef/knife/vault_decrypt.rb
- lib/chef/knife/vault_rotate_all_keys.rb
- lib/chef/knife/vault_update.rb
- spec/chef-vault/certificate_spec.rb
- spec/chef-vault/item_spec.rb
- spec/chef-vault/user_spec.rb
Allow the node name and path to the client key to be specified when calling ChefVault::Item.load.
This supports some use cases that are currently painful in cloud environments.  Refer to issue #150 for more details.
> Allow the node name and path to the client key to be specified

- lib/chef-vault.rb
Currently, chef-vault is loading all of chef, including resources and providers and all kinds of stuff it doesn't actually need. This is triggering an issue in our ChefDK builds where `chef-provisioning` gets required (due to a dubious decision on our part) and then has dependency conflicts with `knife-windows`.
That said, minimizing the number of files required will make chef-vault run faster, which will be nice on its own.
> Only load the parts of chef we actually use

- UPGRADE.md
- features/detect_and_warn_v1_vault.feature
- features/step_definitions/chef-vault.rb
- lib/chef-vault/exceptions.rb
- lib/chef-vault/item_keys.rb
and direct people to a document describing how to manually fix the missing metadata.
> Detect when trying to manage a v1 vault

- lib/chef-vault/chef_patch/api_client.rb
Some chef servers send a field with the key 'name' instead of the field 'clientname'  in their response. If the name of the client isn't correct the data will be stored the wrong way, so that the client won't be able to decrypt.
> add recognition of 'name' in response

- README.md
I created a blog post detailing what Chef Vault is, how it works, how you use it, and its limitations.  I've added it to the README so that new Chef Vault users can find it easily.
> adds link to Chef Vault blog post to README

- UPGRADE.md
Spotted a small typo when reading through the doc. Figured it probably meant to say what it says on [line 10](https://github.com/chef/chef-vault/blame/master/UPGRADE.md#L10), so here's a quick fix
> UPGRADE: fixed a typo

- lib/chef-vault/item.rb
- spec/chef-vault/item_spec.rb
When doing a refresh, saving the encrypted secret is useless since
neither the secret, neither the shared key has changed.
Before this patch, the IV was not reused and the encrypted data changed
on each refresh operation.
This improves partially #193 .
> Only save keys on refresh operation

- features/step_definitions/chef-vault.rb
- features/vault_update.feature
- lib/chef-vault/item.rb
- lib/chef/knife/vault_update.rb
`knife vault update` subcommand does 2 things
* Can update the vault's item value(s)
* Can update the item keys list (Nodes, via `search-query`, or Admins)
Or both in the same command
```ruby
knife vault update VAULT ITEM [-S ] [-A]
```
However, it saves the whole `vault_item` objects ( `${item}` and `${item_keys}` data bag items) even if only clients or admins are provided  ( `${item_keys}`).
This PR goes along e87c70c and issue : https://github.com/chef/chef-vault/issues/193
It is needed when your source of truth is your VCS, and you update your Chef-server via files sync.
> Feature - knife vault update - update item_keys only when no value is provided

- lib/chef/knife/vault_create.rb
Recent patch in chef (released in 12.8.1) raises a new exception when
checking an non-existent item in solo mode.
We need to catch this exception to allow vault item creation.
Kinda fix #203
> Correct vault creation in solo mode

- README.md
If there is a table with the switches for the command, --clean should be
there.
> Fixes #211: Documents --clean switch

- KNIFE_EXAMPLES.md
- README.md
- lib/chef-vault/item.rb
- lib/chef/knife/vault_clients.rb
- lib/chef/knife/vault_create.rb
- lib/chef/knife/vault_remove.rb
- lib/chef/knife/vault_update.rb
- spec/chef-vault/item_spec.rb
Before finishing up this PR I would like some feedback about the feasibility of getting this functionality merged in `chef-vault`?
The reason we have a need for this is because we would like the [Terraform `chef` provisioner](https://www.terraform.io/docs/provisioners/chef.html) to be able to add single clients in the same way as `knife bootstrap` currently does. `knife bootstrap` does this by directly calling/using the `chef-vault` package, but that approach is not possible for the `chef` provisioner.
So [currently](https://github.com/hashicorp/terraform/blob/master/builtin/provisioners/chef/resource_provisioner.go#L559-L591) we add `clients` as `admins`, but of course this has all kinds of nasty side effects and is now how `chef-vault` should be used so people are [not …
> Add support for clients

- bin/chef-vault
- lib/chef-vault.rb
- lib/chef-vault/certificate.rb
- lib/chef-vault/chef_key.rb
- lib/chef-vault/item.rb
- lib/chef-vault/user.rb
- lib/chef/knife/decrypt.rb
- lib/chef/knife/encrypt_create.rb
- lib/chef/knife/encrypt_delete.rb
- lib/chef/knife/encrypt_remove.rb
- lib/chef/knife/encrypt_rotate_keys.rb
- lib/chef/knife/encrypt_update.rb
- lib/chef/knife/vault_base.rb
- lib/chef/knife/vault_decrypt.rb
- lib/chef/knife/vault_rotate_all_keys.rb
- lib/chef/knife/vault_update.rb
- spec/chef-vault/certificate_spec.rb
- spec/chef-vault/item_spec.rb
- spec/chef-vault/user_spec.rb
also switch to using knife ui methods where applicable
Fixes: #53
> Move to using a logger for all user output

- lib/chef-vault.rb
- lib/chef-vault/actor.rb
- lib/chef-vault/item.rb
- lib/chef-vault/item_keys.rb
- spec/chef-vault/actor_spec.rb
- spec/chef-vault/item_keys_spec.rb
- spec/chef-vault/item_spec.rb
This just lets us add a bit of clarity around the use of the class.
cc @tylercloke
> rename ChefKey to Actor

- .gitignore
- lib/chef-vault/item.rb
- lib/chef/knife/vault_create.rb
- lib/chef/knife/vault_update.rb
- spec/chef-vault/item_spec.rb
This shows about a 40% improvement in run times when using `clean-unkown-clients` with refresh.
> Minimize the number of searches

- lib/chef-vault/item_keys.rb
- lib/chef-vault/mixins.rb
- spec/chef-vault/item_keys_spec.rb
> Add feature to save each key in different data bag item

- features/isvault.feature
- features/step_definitions/chef-vault.rb
- features/vault_create.feature
- features/vault_list.feature
- lib/chef-vault/item_keys.rb
- lib/chef/knife/vault_base.rb
- lib/chef/knife/vault_create.rb
- spec/chef-vault/item_keys_spec.rb
This pull request follows #246, hopefully solving #237.
> Vault creation, list, and destruction in sparse mode

- chef-vault.gemspec
- lib/chef-vault/version.rb
The rubygem old ones are angry that our depepdencies are expressed
correctly, so stop doing so.
> Change the chef dependency to development only

- lib/chef/knife/vault_edit.rb
> Replace edit_data() with edit_hash() in vault_edit.rb

- lib/chef-vault/item.rb
The default index.max_result_window for Elasticsearch is 10k. This leads to errors like:
2017-05-03_19:36:41.82788 Caused by: QueryPhaseExecutionException[Result window is too large, from + size must be less than or equal to: [10000] but was [100000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.]
Signed-off-by: Bryan McLellan <btm@loftninjas.org>
> Reduce the search response limit from 100k to 10k

- lib/chef-vault/item_keys.rb
Sparse mode is marked in xxx_keys item with:
> mode: "sparse"
but when decrypting secrets, each node is trying to read the sparse format first
(xxx_key_[node]) and then fallback to normal xxx_keys.
This adds a performance penalty both on reading secrets and during refresh.
With this patch, sparse format is checked only when secret is marked as sparse.
This makes refresh a fast no-op (it was already a no-op with
https://github.com/chef/chef-vault/pull/269 now it is faster) since the only
cost is now searching nodes matching search_query.
> Make sure sparse mode is used on secrets where it is explicit

- features/clean_on_refresh.feature
- features/clean_unknown_clients.feature
- lib/chef-vault/item.rb
Previously we checked if nodes were matching search query AND had an existing chef key.
This patch assumes that all nodes have exiting chef keys.
Experience I have with chef is that nodes without proper keys are bugs and needs
to be fixed anyway (either have a key or be removed).
This patch allows to make usage of --clean-unknown-clients much faster (avoid
querying chef-server for each node) especially on secrets encrypted for many
nodes (where search query time is small compared to querying all clients)
> Assume all nodes matching the search query are valid nodes

- lib/chef-vault/item_keys.rb
Before this patch, every call to ChefVault::Item.load used to call the
chef server for sparse key twice:
- once to load keys
- once to decrypt symetrical key
This has a huge cost on secret read for nodes whose latency to the chef
server is high (we have example with ~300ms ping time).
This patch make sure we don't try to read sparse key when the secret is
marked as non sparse.
> Avoid sparse key read for non sparse secrets

- lib/chef/knife/vault_create.rb
Similar to GH-274, replaces the usage of edit_data with edit_hash to fix
errors in chef 13 and warnings in chef 12.
> Fix fatal error during create

- lib/chef-vault/item.rb
- lib/chef-vault/item_keys.rb
- spec/chef-vault/item_keys_spec.rb
- spec/chef-vault/item_spec.rb
Before this patch, symetrical key was encrypted for all clients on refresh.
With this patch, we only encrypt symetrical key for new clients and re-use previously encrypted key.
This patch requires to improve "vault remove" scenario to clear encrypted data before re-encrypting.
Change-Id: I0abccb32d45deb6ae51a1afdaff54c1e7c994e29
> Avoid re-encrypting key for all existing clients

- features/clean_on_refresh.feature
- lib/chef-vault/item.rb
- lib/chef-vault/item_keys.rb
- lib/chef/knife/vault_refresh.rb
- spec/chef-vault/item_keys_spec.rb
During a refresh operation, speed optimization lead to avoid
re-encrypting symetrical key for each existing clients.
This lead to issues when clients change their chef key.
This patch adds an option --skip-reencryption to workaround that for
users having such behavior.
Fix #286
Change-Id: I0ffa71934d29198fa71aa6e1a9630ad302e21f6a
> Allow to force reencryption of keys during refresh

- chef-vault.gemspec
I don't know of any reason why specs and BDD features would be needed in a runtime setting, let alone a lot of the markdown documentation. Clearly the license should always remain with the code, but that's about it.
Removing all of those brought the file size of the `chef-vault-*.gem` file down from 52KB to 21KB with no functional changes at runtime.
> Only include necessary files when making a gem

- README.md
This section is outdated since we already released 3.0 without the
mentioned features.
Fix #293
Change-Id: Ib219d8ac6def19041761df4627ecdc252fc37ef2
> Remove "future" section from README.md

- features/vault_create.feature
- lib/chef-vault/item.rb
- spec/chef-vault/item_spec.rb
Wording was misleading since we raise the error when the public key is
missing.
Fix #295
> Correct error message when missing public key

- lib/chef-vault/item.rb
Sometimes, when the host has been re-registered, but `knife vault refresh` has not yet been launched, the `@raw_data` may contain a hash item with a value of `nil`:
{ ..., "name.of.the.host" => nil, ... }
In this case `@keys.include?(@node_name)` in `secret` method returns `true`, but `Base64.decode64(@keys[@node_name])` call leads to crash with "undefined method `unpack' for nil:NilClass" error.
Signed-off-by: Dmytro Shapovalov <shad@shad.in.ua>
> Fix undefined method unpack for nil class error

- Changelog.md
- lib/chef/knife/vault_remove.rb
Environment:
```
$ chef -v
Chef Development Kit Version: 3.1.0
chef-client version: 14.2.0
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.4
kitchen version: 1.22.0
inspec version: 2.1.72
$ chef gem list --local chef-vault
*** LOCAL GEMS ***
chef-vault (3.3.0)
```
Before patch:
```
$ knife vault show test-vault test-creds --format json
{
"id": "test-creds",
"_default": {
"username": "kitchen_user",
"password": "kitchen_password"
},
"staging": {
"username": "staging_user",
"password": "staging_password"
},
"production": {
"username": "production_user",
"password": "production_password"
}
}
$ knife vault remove test-vault test-creds '{"staging": {"username": "staging_user", "password": "staging_password"}}' -VV
Traceback (most recent call last):
11: …
```
> Fix FrozenError when calling 'knife vault remove'

- chef-vault.gemspec
There's no need for this in a gem. It just make the install that much
bigger.
> Don't ship the readme in the gem

- README.md
Add documentation for sparse mode
Adding documentation for https://github.com/chef/chef-vault/issues/237
> add documentation for sparse mode

- lib/chef-vault/item_keys.rb
When creating a vault item we get an OpenSSL::PKey::RSAError error when the user or client
keys were generated from a version of chef-server before chef-server 12. The error raised
has no useful information for solving the problem. Pre chef-server 12
public keys are certificates instead of public keys. This change identifies the
user or client with an invalid public key. The key needs to be recreated, any existing
vault items used by the server need to be refreshed after the key is generated.
Creates an error message that can be used.
[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant]
> Send a better error message when an invalid SSL key is encountered when creating a vault item

- lib/chef-vault/item.rb
This PR avoids 2 YARD warnings output when generating documentation, by using the right parameter names.
<details>
```
lib/chef-vault/item.rb:441: [UnknownParam] @param tag has unknown parameter name: client
lib/chef-vault/item.rb:463: [UnknownParam] @param tag has unknown parameter name: client_or_node
```
</details>
...
> API docs: Fix YARD warnings

- lib/chef-vault/item.rb
An empty array or an empty string is not considered false
so no exception is raised when item.search is empty. Which
means we get an HTTP error instead of the expected exception.
This change checks if search is empty instead of just checking if it the false value.
Fixes #312
> Ensure search is not empty when refreshing

- Rakefile
- chef-vault.gemspec
- features/step_definitions/chef-vault.rb
- features/step_definitions/chef_databagitem.rb
- hooks/pre-commit
- lib/chef-vault/actor.rb
- lib/chef-vault/item.rb
- lib/chef-vault/item_keys.rb
- lib/chef-vault/mixins.rb
- lib/chef/knife/mixin/helper.rb
- lib/chef/knife/vault_base.rb
- lib/chef/knife/vault_create.rb
- lib/chef/knife/vault_download.rb
- lib/chef/knife/vault_refresh.rb
- lib/chef/knife/vault_update.rb
- spec/chef-vault/actor_spec.rb
- spec/chef-vault/item_spec.rb
Remove long EOL'd Ruby release support that we're not actually testing
> Drop Ruby 2.2/2.3 support and resolve Chefstyle warnings

- README.md
Fixed ending data bag item names in '_keys' confuses the the parser
Fixed: https://github.com/chef/chef-vault/issues/228
> Added note in documentation regarding the vault item name

- Gemfile
- chef-vault.gemspec
- lib/chef-vault/item.rb
Fixed 'vault?' method should throw meaningful exception when no data bag exists
Fixed: https://github.com/chef/chef-vault/issues/278
> Handled exception from vault? method

- lib/chef-vault/actor.rb
- lib/chef-vault/item.rb
require is quite slow in Ruby and doing requires for things you've already required is also slow. We've used this simple hack in Chef to speed up our requires. In the omnibus installs we patch how rubygems works to make this somewhat pointless, but this will help non-omnibus installs
> Optimize requires for non-omnibus installs

- lib/chef/knife/vault_admins.rb
Added warning if input of vault admin is other than array
Fixed: https://github.com/chef/chef-vault/issues/219
> Added warning if input of vault admin is other than array

- lib/chef/knife/vault_list.rb
- lib/chef/knife/vault_show.rb
Fixed knife vault show -F json and knife vault list -F json don't always output valid JSON
Fixed: https://github.com/chef/chef-vault/issues/313
> Fixed knife vault show -F json and knife vault list -F json don't always output valid JSON

- lib/chef-vault/exceptions.rb
- lib/chef/knife/mixin/helper.rb
- spec/chef/helper_spec.rb
knife vault : Problem escaping string in JSON
fixed: https://github.com/chef/chef-vault/issues/346
> Fixed problem escaping string in JSON

- bin/chef-vault
- chef-vault.gemspec
- lib/chef/knife/mixin/helper.rb
- lib/chef/knife/vault_admins.rb
- lib/chef/knife/vault_base.rb
Disable the eval cop where we're doing unavoidable things
> Resolve chefstyle warnings

- lib/chef/knife/vault_base.rb
With 10k secrets the regexp union is quite big and applying it to
the 20k keys takes around 2 minutes...
Also the Regexp was too greedy and could match normal items as sparse
one.
This is a copy of https://github.com/chef/chef-vault/pull/362 without the style fixes
Signed-off-by: Baptiste Courtois <b.courtois@criteo.com>
> Optimize split_vault_keys method for large bag

- Gemfile
- lib/chef-vault/item.rb
- lib/chef/knife/vault_delete.rb
Build was failing for `contracts `and `chef-utils` gem dependencies
https://buildkite.com/chef-oss/chef-chef-vault-main-verify/builds/114
Signed-off-by: jayashri garud <jgarud@msystechnologies.com>
https://github.com/chef/release-engineering/issues/1607
> fix-verify-pipeline

- lib/chef/knife/mixin/helper.rb
- spec/chef/helper_spec.rb
When uploading vault item that contains \n errors with the below message.
Check that backslashes are escaped with another backslash (e.g. C:\Windows) in double-quoted strings.
Looking at that error, we changed the \n to \n and the error stops BUT the content vault item actually have \n and no new line is inserted.
Before Fix: 
```
bundle exec knife vault update test test1 -J ../../chef-repo/root.json -c ../../chef-repo/.chef/knife.rb
ERROR: ChefVault::Exceptions::InvalidValue: Value 'my
passwords' of key 'text1' contains non-printable characters. Check that backslashes are escaped with another backslash (e.g. C:\\Windows) in double-quoted strings.
bundle exec knife vault show test test1 -c ../../chef-repo/.chef/knife.rb
id: …
```
> Replaced exception with the warnings and removed related failing specs(used earlier for raising issue)

- lib/chef/knife/vault_create.rb
- lib/chef/knife/vault_remove.rb
- lib/chef/knife/vault_update.rb
Right now any knife plugin even `knife -h` will load all these plugins and end up loading all of chef-vault. This avoids 11 requires total.
> Avoid loading all of chef-vault unless we're running the plugin

- README.md
- features/step_definitions/chef-repo.rb
- features/step_definitions/chef-vault.rb
- features/vault_show.feature
- lib/chef-vault/item.rb
- spec/chef-vault/item_spec.rb
adds support for chef-vault to use the private key from the client_key_contents chef configuration option
#401
> add support for client_key_contents

- .expeditor/verify.pipeline.yml
- .github/workflows/unit.yml
- Gemfile
- Rakefile
- chef-vault.gemspec
- lib/chef/knife/mixin/helper.rb
- spec/chef/helper_spec.rb
Fixing the warning message for sensitive info in json like passwords and json validation for non-printable characters
https://progresssoftware.atlassian.net/browse/CHEF-3710
> CHEF-3710-chef-vault warning message includes sensitive info

- .expeditor/verify.pipeline.yml
- .github/workflows/unit.yml
- Gemfile
- Rakefile
- chef-vault.gemspec
- habitat/plan.ps1
- habitat/plan.sh
- lib/chef-vault/version.rb
Added the plan.sh and plan.ps1 file to build package chef-vault as a hab package.
> Package chef-vault as an hab package

- .expeditor/config.yml
- .expeditor/run_windows_tests.ps1
- .expeditor/verify.pipeline.yml
- .github/workflows/unit.yml
- .gitignore
- Gemfile
- Rakefile
- dev/Dockerfile.linux
- dev/Dockerfile.windows
- dev/readme.md
> Rubocop correction

- Gemfile
- features/step_definitions/chef-repo.rb
- features/support/env.rb
`@aruba_timeout_seconds` is depreciated so updated the code with latest Aruba configuration to set the timeout.
Also updated the timeout for windows platform since the cucumber scenarios take more time execution in the windows platform.
> Fixing windows verify pipeline

- .expeditor/verify.pipeline.yml
- features/support/env.rb
Updating the timeout for the verify pipeline to 120 min
> Updating the timeout for the verify pipeline to 120 min
