- Changelog.md
- KNIFE_EXAMPLES.md
- README.md
- features/step_definitions/chef-vault.rb
- features/vault_show_vaultname.feature
- lib/chef/knife/vault_base.rb
- lib/chef/knife/vault_list.rb
- lib/chef/knife/vault_show.rb
Enhance 'knife vault show' so that it when called with just a vault name, it returns a list of items in that vault
This brings 'knife vault show' up to par with 'knife data bag show'
Closes #141
> Enhance 'knife vault show' to list vault items

- .rubocop_todo.yml
- Changelog.md
- KNIFE_EXAMPLES.md
- README.md
- features/isvault.feature
- features/itemtype.feature
- features/step_definitions/chef-databag.rb
- features/step_definitions/chef-vault.rb
- features/step_definitions/chef_databagitem.rb
- lib/chef-vault/item.rb
- lib/chef/knife/vault_isvault.rb
- lib/chef/knife/vault_itemtype.rb
- spec/chef-vault/item_spec.rb
Add a vault? predicate to ChefVault::Item that returns true if an item appears to be a vault
Add a data_bag_item_type method to ChefVault::Item that returns :normal, :encrypted or :vault
Add 'knife vault isvault VAULT ITEM' subcommand
Add 'knife vault itemtype VAULT ITEM' subcommand
Add documentation coverage badge from http://inch-ci.org to README
> Add vault probing predicates

- .travis.yml
- README.md
> Add gitter.im

- lib/chef-vault/item.rb
- lib/chef-vault/item_keys.rb
- lib/chef-vault/mixins.rb
- spec/chef-vault/item_keys_spec.rb
This was introduced in Chef 12. Fixes #191
> Correctly handle an array of data_bag paths

- .travis.yml
- chef-vault.gemspec
- lib/chef-vault/version.rb
Signed-off-by: Thom May <thom@may.lt>
> Ready first chef-vault 3.0 RC

- lib/chef-vault/item.rb
- spec/chef-vault/item_spec.rb
This is based on @tfheen's work in #178, and a suggestion from
@rveznaver in #237
Initial benchmarking with 100 nodes suggests running `knife vault create` or `knife vault refresh` use about 40% of the memory on the client than 2.9. All operations run somewhat faster; refresh is about 20 seconds faster.
Further benchmarking to follow
> Optimise queries when finding nodes

- lib/chef/knife/mixin/helper.rb
> Use legacy solo mode

- Gemfile
- spec/chef-vault/item_keys_spec.rb
- spec/chef-vault_spec.rb
This should increase coverage and prepare the test bed for #237
> Enable testing with Chef Zero

- Gemfile
- lib/chef-vault/version.rb
Signed-off-by: Thom May <thom@chef.io>
> bump g-h-c version

- Changelog.md
- Gemfile
- lib/chef-vault/version.rb
- tasks/github_changelog_generator.rb
Signed-off-by: Thom May <thom@chef.io>
> Prepare for 3.0 release

- chef-vault.gemspec
- lib/chef-vault/version.rb
and fix pre-release detection (again)
> Start working on 3.2.0

- .travis.yml
- README.md
> Add documentation of databags_fallback

- chef-vault.gemspec
We need this for appbundler this gem in ChefDK
> Ship the gemfile in the gem

- chef-vault.gemspec
More tweaks to the gemspec to ship the necessary files for ChefDK
> Fix license string in gemspec + ship gemspec / readme

- lib/chef-vault/item.rb
- lib/chef-vault/item_keys.rb
- lib/chef/knife/vault_update.rb
- spec/chef-vault/item_keys_spec.rb
This adds a feature to convert from default mode to sparse mode
> Sparse mode converter

- .rubocop.yml
- .simplecov
- lib/chef/knife/vault_rotate_all_keys.rb
Fixed knife rotate all keys -- rotates a deleted key
Fixed: https://github.com/chef/chef-vault/issues/257
`bundle exec knife vault rotate all keys -c ../../chef-repo/.chef/knife.rb`
`Rotating keys for: pass user_keys_details_keys`
`ERROR: ChefVault::Exceptions::KeysNotFound: pass/user_details_keys_keys could not be found`
`bundle exec knife vault rotate all keys -c ../../chef-repo/.chef/knife.rb`
`Rotating keys for: pass user_keys_details`
> Replaced string with regex in sub method

- .expeditor/config.yml
- .expeditor/run_linux_tests.sh
- .expeditor/verify.pipeline.yml
> Update expeditor config for new gem caching

- lib/chef-vault/item.rb
- lib/chef/knife/vault_delete.rb
Signed-off-by: nikhil2611 <nikhilgupta2102@gmail.com>
Added back the begin and end statement as ruby 2.4 don't supports rescue inside the do end block. 
Fixes #378
> added back the begin and end

- bin/chef-vault
- lib/chef-vault/item.rb
- spec/chef-vault/item_spec.rb
Signed-off-by: snehaldwivedi <sdwivedi@msystechnologies.com>
any output was not written for chef-vault command so added to get the result
https://github.com/chef/chef-vault/issues/373
> Fix for chef-vault command was not returning any results

- .github/CODEOWNERS
Signed-off-by: Vikram Karve <vikram.karve@progress.com>
this repo will be maintained by the workstation team going forward so need ability to approve and merge PRs.
https://github.com/chef/chef-oss-practices/pull/354
> Add workstation team as code-owner

- .expeditor/run_windows_tests.ps1
- .expeditor/verify.pipeline.yml
- spec/chef-vault/item_keys_spec.rb
Signed-off-by: nikhil2611 <nikhilgupta2102@gmail.com>
Added  ruby 3.0 and 3.1 test for windows
> Added windows test for ruby 3.0 and 3.1

- .expeditor/run_windows_tests.ps1
- .expeditor/verify.pipeline.yml
- Gemfile
- Rakefile
- chef-vault.gemspec
> Fixing verify test failure

- .expeditor/build.habitat.yml
- .expeditor/buildkite/artifact.habitat.test.ps1
- .expeditor/buildkite/artifact.habitat.test.sh
- .expeditor/config.yml
- .expeditor/habitat-test.pipeline.yml
- habitat/tests/test.sh
> [CHEF-17477] Buildkite pipelines for building and verifying hab pkgs

- .expeditor/config.yml
- .expeditor/verify.pipeline.yml
The workstation LTS changes have been merged into the workstation-LTS branch. This PR will add that to the release branches to build habitat packages.
> Include workstation-LTS branch to the release branches.

- .expeditor/verify.pipeline.yml
> Reverted the change that was added by mistake

- .expeditor/config.yml
Adding pipelines to trigger pipeline automatically
> Adding pipelines to trigger pipeline automatically

- .github/workflows/ci-main-pull-request-checks-stub.yml
- .github/workflows/sonarqube.yml
- .github/workflows/unit.yml
Fixing the security scanning warnings, This PR fixes the following security issues:
https://github.com/chef/chef-vault/security/code-scanning/3
https://github.com/chef/chef-vault/security/code-scanning/2
https://github.com/chef/chef-vault/security/code-scanning/1
> Fixing the security scanning warnings

- .github/workflows/ci-main-pull-request-stub.yml
Fixing Workflow does not contain permissions warnings, This PR fixes the following security issues:
https://github.com/chef/chef-vault/security/code-scanning/7
https://github.com/chef/chef-vault/security/code-scanning/6
> Fixing Workflow does not contain permissions warnings

- .expeditor/config.yml
Commenting out Habitat package promotion to publish chef-vault gem to the rubygems.org
> Commenting out Habitat package promotion to publish chef-vault gem first 
